### ISSUE TITLE
problem starting up

### ISSUE THREAD

**Issue by dberardo-com** [jpatacas/bim2twin#1]
npm start --> 

![image](https://github.com/jpatacas/bim2twin/assets/65530457/d9cf3419-e160-4043-bece-a4b8119fe994)

**Comment by dberardo-com** [comment]
is there a live demo or some screenshots of how the result should look like ?

**Comment by jpatacas** [comment]
Please look at the Readme file for the project, under "Firebase configuration"

- you need to add a config.js file in /src with your firebaseConfig data and Mapbox API key
